spring:
  application:
    name: APPOINMENTSASTURIAS
  profiles:
    active: prod
#  banner:
#    location: classpath:Banner.txt

  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DATABASE_PASSWORD:password}
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/appointments_asturiasDB}
    username: ${DATABASE_USERNAME:postgres}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      show-sql: true



server:
  port : 8080


